name: TournoiMC
version: 1.6
api-version: 1.19
author: JacquelineDuGame
main: fr.jacquelinedugame.tournoimc.Main
commands:
  startspeedrun:
    description: Permet de lancer le tournoi
    permission: tournoimc.startspeedrun.use
  createteam:
    description: Permet de creer une team et ajoute le joueur
    permission: tournoimc.createteam.use
  jointeam:
    description: Permet de rejoindre une team
    permission: tournoimc.jointeam.use
  leaveteam:
    description: Permet de quitter une team si la partie n as pas encore commence
    permission: tournoimc.leaveteam.use
  finishspeedrun:
    description: Permet de terminer une partie de speedrun
    permission: tournoimc.finishspeedrun.use
  sendcoords:
    description: Permet d envoyer ses coordonnees a son equipe
    permission: tournoimc.sendcoords.use
  resetspeedrun:
    description: Permet de reset le speedrun
    permission: tournoimc.resetspeeedrun.use
  fautfairequoi:
    description: Permet de savoir quoi faire pour le tournoi
    permission: tournoimc.fautfairequoi.use
  stopjoin:
    description: Permet de bloquer ou debloquer le serveur quand la partie a commence
    permission: tournoimc.stopjoin.use